apiVersion: apps/v1
kind: Deployment
metadata:
  name: anwar
spec:
  # pod selector 
  # replicas
  # pod teplate
  replicas: 3
  selector:
    matchLabels:
       env: prod

  template:
     metadata:
       labels:
         env: prod

     spec:
       containers:
       - name: nginx
         image: nginx
