apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config-file
data:
# add configmap as a file
# a file test.conf
# same do in secret
   test.conf: |
     log_test stdout 
     log_type all
     log_timestamp true
     listener 9001 

#template:  --> pod
#  metadata:
#    labels: 
#       app: mosquitto
#  spec:
#   containers:
#     - name: mosquitto
#      image: eclipse-mosquitto:1.6.2
#      ports:
         - containerPort: 1883
       volumeMounts:
         - name: mosquitto-config
           mountPath: /mosquitto/config  # add the file in configmap name mosquitto-config in a container in this path inside a container and same in secret
         - name: mosquitto-secret
           mountPath: /mosquitto/secret
   volumes: # this volumes for a pod
     - name: mosquitto-config  # this mean i need to add a volume mosquitto-config and read a configmap mosquitto-config-file and same in secret
       configMap:
         name: mosquitto-config-file
     - name: mosquitto-secret
       secret:
         secretName: mosquitto-secret-file
